Fname = input("Enter First Name: ")
Lname = input("Enter Last Name: ")
Mname = input("Enter Middle Name: ")
Bday = input("Enter Birthdate: ")
Gender = input("Gender: ")
Address = input("Enter Address: ")
Course = input("Enter Course: ")
Year = input("Enter Year Level: ")

print("\nFirst Name: ", Fname)
print("Last Name: ", Lname)
print("Middle Name: ", Mname)
print("Birthdate: ", Bday)
print("Gender: ", Gender)
print("Address: ", Address)
print("Course: ", Course)
print("Year Level: ", Year)